version: "3.8"
services:
  postgres:
    image: 'postgres'
    volumes:
      - data:/data/db
    #environment:
    # - init_username: admin
    #  - init_password: admin
  todolist:
    build: ./todolist
    ports: 
      - '8081:8080'
    volumes:
      - logs:/app/logs
    depends_on:
      - postgres
    
    
    
